version: '3'

services:
  wahhoi-api:
    build:
      context: ./wahhoi-api/
    ports:
      - 8080:8080
    links:
      - db
  wahhoi-store:
    build:
      context: ./wahhoi-store/
      volumes:
        - ./wahhoi-store/mysql_data:/var/lib/mysql
        - ./wahhoi-store/sqls:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - 3306:3306
