version: '3'

networks:
  app-tier:
    driver: bridge

services:
  api:
    build:
      context: ./wahhoi-api/
    environment: 
      - "spring.datasource.url=jdbc:mysql://${STORE_HOST}:3306/wahhoi"
      - "spring.datasource.username=root"
      - "spring.datasource.password=${MYSQL_ROOT_PASSWORD}"
      - "spring.datasource.driverClassName=com.mysql.jdbc.Driver"
    ports:
      - 8080:8080
    networks: 
      - app-tier
    extra_hosts: 
      - "${STORE_HOST}:${MY_ADDR}"
    links:
      - store
  store:
    build:
      context: ./wahhoi-store/
    volumes:
      - ./wahhoi-store/mysql_data:/var/lib/mysql
      - ./wahhoi-store/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks: 
      - app-tier
