version: 2

jobs:
  build_wahhoi:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install \
              python-pip
            sudo pip install \
              awscli
      - restore_cache:
          keys:
            - wahhoi-test-{{ .Branch }}
          paths:
            - ~/caches/wahhoi.tar
      - run:
          name: Load Docker Image Layer from Cache
          command: |
            set +o pipefail
            docker load -i ~/caches/wahhoi.tar | true
      - run:
          name: gradlew build
          command: |
            chmod +x ./gradlew
            ./gradlew build -x test
          working_directory: wahhoi-api
      - run:
          name: docker build
          command: docker build -t wahhoi:tmp .
          working_directory: wahhoi-api
      - run:
          name: Save Docker Image Layer to Cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/wahhoi.tar wahhoi:tmp
      - save_cache:
          key: wahhoi-test-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/wahhoi.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag wahhoi:tmp "${ECR_ENDPOINT}:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}:${CIRCLE_SHA1}"
            fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_wahhoi