apiVersion: apps/v1
kind: Deployment
metadata:
  name: wahhoi
  namespace: wahhoi
spec:
  selector:
    matchLabels:
      app: wahhoi
  template:
    metadata:
      labels:
        app: wahhoi
    spec:
      containers:
      - name: wahhoi
        image: 659905521232.dkr.ecr.us-west-2.amazonaws.com/wahhoi:0d98156c616696e0c8555fca19c486d7a8fb1189
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: SPRING_DATASOURCE_URI
            value: "jdbc:mysql//db.wahhoi.gdx.local:3306"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "letswahhoi"
          - name: SPRING_DATASOURCE_DRIVERCLASSNAME
            value: "com.mysql.jdbc.Driver"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wahhoi
  namespace: wahhoi
spec:
  selector:
    app: wahhoi
  ports:
  - port: 80
    targetPort: 8080

