version: '3'

services:
  wahhoi-store:
    build:
      context: .
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
